### ISSUE TITLE
Failing to deploy

### ISSUE THREAD

**Issue by MikeJohnPage** [malteserteresa/stop-it#6]
I tested the models on both Ubuntu 18.04 and MacOS Mojave 10.14 and they failed with the same error messages.

Running `python model.py` failed:
```
Traceback (most recent call last):
  File "model.py", line 211, in <module>
    model = build(train, save_model=True)
  File "model.py", line 124, in build
    model.save(os.getcwd() +'/saved_model_data/model/model_' + now + '.h5')
  File "/home/mike/anaconda3/envs/stop-it/lib/python3.7/site-packages/tensorflow/python/keras/engine/sequential.py", line 319, in save
    save_model(self, filepath, overwrite, include_optimizer)
  File "/home/mike/anaconda3/envs/stop-it/lib/python3.7/site-packages/tensorflow/python/keras/engine/saving.py", line 93, in save_model
    f = h5py.File(filepath, mode='w')
  File "/home/mike/anaconda3/envs/stop-it/lib/python3.7/site-packages/h5py/_hl/files.py", line 394, in __init__
    swmr=swmr)
  File "/home/mike/anaconda3/envs/stop-it/lib/python3.7/site-packages/h5py/_hl/files.py", line 176, in make_fid
    fid = h5f.create(name, h5f.ACC_TRUNC, fapl=fapl, fcpl=fcpl)
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py/h5f.pyx", line 105, in h5py.h5f.create
OSError: Unable to create file (unable to open file: name = '/home/mike/Documents/projects_ds/other_projects/tess/stop-it/saved_model_data/model/model_2019-04-22 16:00:55.065755.h5', errno = 2, error message = 'No such file or directory', flags = 13, o_flags = 242)
```
Running `python deploy.py` failed:

```
Traceback (most recent call last):
  File "deploy.py", line 9, in <module>
    from model import test, create_dictionary
ImportError: cannot import name 'test' from 'model' (/home/mike/Documents/projects_ds/other_projects/tess/stop-it/model.py)
```

**Comment by malteserteresa** [comment]
A typo, I went around renaming things, shall push the changes soon
